language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_script:
- npm install grunt-cli -g
- npm install bower -g
- npm install bower-installer -g
- chmod +x ./deploy-gh-pages.sh
script: ./deploy-gh-pages.sh
env:
  global:
  - GH_REF=github.com/PJL101/iampjl.co.uk.git
  - secure=Bz8HH1Du4WdoaLx1afUMPegZyCwsBOFexAfxgWrBbmtuN4Qe+ZOZ7J1lYek6hjI4F03A6DkQXz2xNXX7mxAOb7cyvk2oC6PQZXwuItC5ngU1mm4aXqcSvHVmpixGrK9Rd7RCfGjR9fcOZzY4mQ/GGkXw8HKEdBc/zZ6lj5L9/UCuwmavMzkfX0lz1s24uwygoIY9cLDg32fKisqqYHPQDEgYNlHheHRsbRyj5G5pvZc9MQeNv16QrGL3p1Q0IMSvjmPLyJaXyKGh2zzJN/EuP1eOz2JFBO/bFAa7jPuUocaSD8xbHsz3FpECv6zo2CLW7HBzpWTCPfXKxjZSjeHzO2EWPTeL9FAk2BH81xENhr70FZjohTPYEFzaUlDVZI35U6QxDbsA1Mpbr2NXitGa70ZeGg9tOkU/q4kmRtjaDCaka1/aHWPmP5zmcaQQooL4xXKA1m6BsBUNoZi2Q0DwQ5louR28ooX8iYUG6e/Hyvl1oCCb98K8lgukVXs2FHu4he4wDKU4PGbkdPPHH4m9LoTKmqCPPcVQ3BY6WukNtgHro6Qjv2lN1QjYxRrzE1nBz/fYh6eWMKmHISMP5Bp9ymgI/So9wPWHeYIxboomcUHGzD6UxdyNqnnWcOi3g0PmpAWF03WawSUJZfmOWKwXa49MjdfDy4mAAH5lBsCO2Eo=
