language: node_js
node_js:
  - 'iojs'
branches:
  only:
  - master
before_script:
- npm install grunt-cli -g
- npm install bower -g
- npm install bower-installer -g
- chmod +x ./deploy-gh-pages.sh
script: ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: "github.com/PJL101/PJL101.github.io.git"
  - secure: "bTkWzsvzjrYgndgzhJ+2ADzOwX0B+JDzmhUzBjlsIt4s4mDTEUdYqJCMQrDzGS0zFRiRbP5wTsPNJ3iV7CD1hp2Ugi73DmQdjXmWfpyhawVl6MCHdbST0z4MesdJDy5BdToQ9EMEhBAl5zW+GuYPXpxN3uiRvd4On7RUajLHktWa1Y0ujtMgiRjpUUkT9bK5iVySZDEuDRfxjkT9Gvu1xm2LluwO+xvdpWw97NSZyBNQJ3RhSjeihf5OgzC4JqM/SCh8TvqjAAaL2Twi+zw6LHRJm+AERiX7W/6SN7MpmE2w3lOoF5tXiCz+CUjTaEfBTQKtmU135STcaMYRH8fzjdzZR13T1nuv5ahSH9i4kn7W/+SE2M/b91w4Gim2qqbaf/fHyfXDYDv9s30DhB+tOC+bpySr5oExaqxJvoV5x3RK+axKv0twR+7k+5xA0e08P5YT40xOZ8mk3ExgmPpXRYu8QwUG4w9ujHGj0TINO9wNwx3GEnUQrmQ5Foa6CtAr5k3AREXE0dGczlAOAG0Xx+QQeB1DjFk5RC1Ur49F4v5RNrrp2KVQcvNw+5trVUadabKymzM2m0L4iGV7GZ7rOwymoNBM7+CCAwya0fZZqpmU5IQNL9NQeo48U4E4nY2vaDstKGmu1yAn9DzVW3V3R4DDQAnlcLnyYnTgWXOkiek="
