# File Locations
# =============================================

# Build paths
gruntFile:      Gruntfile.js
src:            src
srcAssets:      <%= site.src %>/assets
dist:           _dist
distAssets:     <%= site.dist %>/assets

# Assemble
templates:      <%= site.src %>/templates
data:           <%= site.templates %>/data/*.{json,yml}
helpers:        <%= site.templates %>/helpers/helper-*.js
partials:       <%= site.templates %>/partials/{,*/}*.hbs
layouts:        <%= site.templates %>/layouts/{,*/}*.hbs
pages:          <%= site.templates %>/pages/{,*/}*.hbs
